// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://czaslbgycseyubtzjyah.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN6YXNsYmd5Y3NleXVidHpqeWFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIwODA5MDYsImV4cCI6MjA3NzY1NjkwNn0.IMQ5-nRuAGzboprf8r_G8xfhWJdepylVqV2cceZMTJI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});